In [1]:
import pandas as pd
import numpy as np

In [44]:
a= pd.read_csv("series_by_year.csv")

In [45]:
a.drop("rating", axis=1, inplace=True )

In [40]:
df = pd.read_csv("C:\\Users\\fzehr\\OneDrive\\Belgeler\\GitHub\\WebMiningProject\\asianfanatics\\a.csv")

In [41]:
df

,name,total_episode,rating,like,watch,cast,category
0,Because of You,22.0,7.0,11,3,"[{'name': 'Lego Lee Fang', 'caracter': 'Zi Hao...","Gençlik,Romantik,Tayvan Dizileri"
1,49 Days,20.0,8.4,82,64,"[{'name': 'Jo Hyun-jae', 'caracter': 'Han Kang...","Dram,Fantastik,Romantik"
2,The Slave Hunters,24.0,7.9,46,32,"[{'name': 'Jang Hyuk', 'caracter': 'Lee Dae-gi...","Aksiyon,Dram,Tarih"
3,Secret Garden,20.0,8.9,198,150,"[{'name': 'Hyun Bin', 'caracter': 'Kim Joo-won...","Dram,Fantastik,Komedi"
4,A Man Called God,24.0,6.7,10,9,"[{'name': 'Song Il-gook', 'caracter': 'Michael...","Dram,Romantik"
...,...,...,...,...,...,...,...
1003,Flex X Cop,16.0,9.1,77,32,"[{'name': 'Ahn Bo-hyun', 'caracter': 'Jin I-so...","Aksiyon,Gizem,Suç"
1004,The Midnight Studio,16.0,8.0,62,28,"[{'name': 'Joo Won', 'caracter': 'Seo Ki-joo'}...","Dram,Fantastik,Romantik"
1005,Queen of Tears,16.0,8.6,58,36,"[{'name': 'Kim Soo-hyun', 'caracter': 'Baek Hy...","Dram,Romantik"
1006,Doctor Slump,16.0,8.4,81,44,"[{'name': 'Park Shin-hye', 'caracter': 'Nam Ha...","Dram,Komedi,Romantik"
1007,Pyramid Game,10.0,8.7,46,12,"[{'name': 'Bona', 'caracter': 'Sung Su-ji'}, {...","Aksiyon,Dram,Gençlik,Gerilim"

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1008 entries, 0 to 1007
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           1008 non-null   object
 1   total_episode  932 non-null    float64
 2   rating         1008 non-null   float64
 3   like           1008 non-null   int64
 4   watch          1008 non-null   int64
 5   cast           973 non-null    object
 6   category       1008 non-null   object
dtypes: float64(2), int64(2), object(3)
memory usage: 55.3+ KB

In [47]:
merged_df = pd.merge(df, a, on='name')
merged_df

,name,total_episode,rating,like,watch,cast,category,year,url
0,Because of You,22.0,7.0,11,3,"[{'name': 'Lego Lee Fang', 'caracter': 'Zi Hao...","Gençlik,Romantik,Tayvan Dizileri",2010,https://asyafanatiklerim.com/dizi/because-of-you/
1,49 Days,20.0,8.4,82,64,"[{'name': 'Jo Hyun-jae', 'caracter': 'Han Kang...","Dram,Fantastik,Romantik",2011,https://asyafanatiklerim.com/dizi/49-days/
2,The Slave Hunters,24.0,7.9,46,32,"[{'name': 'Jang Hyuk', 'caracter': 'Lee Dae-gi...","Aksiyon,Dram,Tarih",2010,https://asyafanatiklerim.com/dizi/the-slave-hu...
3,Secret Garden,20.0,8.9,198,150,"[{'name': 'Hyun Bin', 'caracter': 'Kim Joo-won...","Dram,Fantastik,Komedi",2010,https://asyafanatiklerim.com/dizi/secret-garde...
4,A Man Called God,24.0,6.7,10,9,"[{'name': 'Song Il-gook', 'caracter': 'Michael...","Dram,Romantik",2010,https://asyafanatiklerim.com/dizi/a-man-called...
...,...,...,...,...,...,...,...,...,...
1003,Flex X Cop,16.0,9.1,77,32,"[{'name': 'Ahn Bo-hyun', 'caracter': 'Jin I-so...","Aksiyon,Gizem,Suç",2024,https://asyafanatiklerim.com/dizi/flex-x-cop/
1004,The Midnight Studio,16.0,8.0,62,28,"[{'name': 'Joo Won', 'caracter': 'Seo Ki-joo'}...","Dram,Fantastik,Romantik",2024,https://asyafanatiklerim.com/dizi/the-midnight...
1005,Queen of Tears,16.0,8.6,58,36,"[{'name': 'Kim Soo-hyun', 'caracter': 'Baek Hy...","Dram,Romantik",2024,https://asyafanatiklerim.com/dizi/queen-of-tears/
1006,Doctor Slump,16.0,8.4,81,44,"[{'name': 'Park Shin-hye', 'caracter': 'Nam Ha...","Dram,Komedi,Romantik",2024,https://asyafanatiklerim.com/dizi/doctor-slump/
1007,Pyramid Game,10.0,8.7,46,12,"[{'name': 'Bona', 'caracter': 'Sung Su-ji'}, {...","Aksiyon,Dram,Gençlik,Gerilim",2024,https://asyafanatiklerim.com/dizi/pyramid-game/

In [99]:
year_counts = merged_df.groupby('year').size()
year_counts

year
2010      8
2011     16
2012     13
2013     33
2014     51
2015     56
2016     98
2017    128
2018    122
2019    118
2020     93
2021     84
2022     85
2023     79
2024     24
dtype: int64

In [48]:
merged_df[merged_df["total_episode"].isna()]

,name,total_episode,rating,like,watch,cast,category,year,url
25,The Thieves,NaN,8.5,61,35,"[{'name': 'Choi Dong-hoon', 'caracter': 'Yönet...","Aksiyon,Suç",2012,https://asyafanatiklerim.com/film/the-thieves-tr/
86,Set Me Free,NaN,8.5,12,9,"[{'name': 'Kim Tae-yong', 'caracter': 'Yönetme...",Dram,2014,https://asyafanatiklerim.com/film/set-me-free/
136,Wonderful Nightmare,NaN,9.1,17,21,"[{'name': 'Kang Hyo-jin', 'caracter': 'Yönetme...","Dram,Fantastik,Komedi",2015,https://asyafanatiklerim.com/film/wonderful-ni...
242,After the Show Ends,NaN,8.2,77,37,"[{'name': 'Yoon So-hee', 'caracter': None}, {'...","Dram,Fantastik,Romantik",2016,https://asyafanatiklerim.com/dizi/after-the-sh...
261,Train to Busan,NaN,9.2,232,188,"[{'name': 'Yeon Sang-ho', 'caracter': 'Yönetme...","Aksiyon,Gerilim,Korku",2016,https://asyafanatiklerim.com/film/train-to-bus...
...,...,...,...,...,...,...,...,...,...
638,Money,NaN,8.9,27,20,"[{'name': 'Park Noo-ri', 'caracter': 'Yönetmen...",Suç,2019,https://asyafanatiklerim.com/film/money/
639,Miss and Mrs. Cops,NaN,9.4,196,111,"[{'name': None, 'caracter': 'Yönetmen'}, {'nam...","Aksiyon,Komedi",2019,https://asyafanatiklerim.com/film/miss-and-mrs...
641,Hit and Run Squad,NaN,9.0,47,33,"[{'name': None, 'caracter': 'Yönetmen'}, {'nam...","Aksiyon,Suç",2019,https://asyafanatiklerim.com/film/hit-and-run-...
642,Juror 8,NaN,9.3,48,31,"[{'name': None, 'caracter': 'Yönetmen'}, {'nam...","Dram,Gerilim",2019,https://asyafanatiklerim.com/film/juror-8/
880,Confession 2022,NaN,8.5,33,7,"[{'name': 'Yoon Jong-seok', 'caracter': 'Yönet...","Gerilim,Gizem,Suç",2022,https://asyafanatiklerim.com/film/confession-2...

## Filled nan values in total_episode

In [49]:
merged_df.loc[merged_df["url"].str.contains("/film"), "total_episode"] = merged_df.loc[merged_df["url"].str.contains("/film"), "total_episode"].fillna(1)

In [50]:
merged_df[merged_df["total_episode"].isna()]

,name,total_episode,rating,like,watch,cast,category,year,url
242,After the Show Ends,NaN,8.2,77,37,"[{'name': 'Yoon So-hee', 'caracter': None}, {'...","Dram,Fantastik,Romantik",2016,https://asyafanatiklerim.com/dizi/after-the-sh...
311,Bir Doksan (One Ninety),NaN,7.8,77,49,NaN,"Gençlik,Kazakistan Dizileri,Komedi,Romantik",2017,https://asyafanatiklerim.com/dizi/bir-doksan-o...
443,Smile,NaN,8.8,152,86,NaN,"Çin Dizileri,Komedi,Romantik",2018,https://asyafanatiklerim.com/dizi/smile/
604,Kill It,NaN,9.3,298,162,"[{'name': 'Jang Ki-Yong', 'caracter': 'Kim Soo...","Aksiyon,Gizem",2019,https://asyafanatiklerim.com/dizi/kill-it/

In [51]:
merged_df.loc[merged_df["name"] == "After the Show Ends", "total_episode"] = merged_df.loc[merged_df["name"] == "After the Show Ends", "total_episode"].fillna(8)
merged_df.loc[merged_df["name"] == "Bir Doksan (One Ninety)	", "total_episode"] = merged_df.loc[merged_df["name"] == "Bir Doksan (One Ninety)	", "total_episode"].fillna(5)
merged_df.loc[merged_df["name"] == "Smile", "total_episode"] = merged_df.loc[merged_df["name"] == "Smile", "total_episode"].fillna(24)
merged_df.loc[merged_df["name"] == "Kill It	", "total_episode"] = merged_df.loc[merged_df["name"] == "Kill It	", "total_episode"].fillna(12)

In [52]:
merged_df["total_episode"] = merged_df["total_episode"].astype("Int64")

In [53]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1008 entries, 0 to 1007
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           1008 non-null   object
 1   total_episode  1006 non-null   Int64
 2   rating         1008 non-null   float64
 3   like           1008 non-null   int64
 4   watch          1008 non-null   int64
 5   cast           973 non-null    object
 6   category       1008 non-null   object
 7   year           1008 non-null   int64
 8   url            1008 non-null   object
dtypes: Int64(1), float64(1), int64(3), object(4)
memory usage: 72.0+ KB

## create new column by movie or serie

In [54]:
def determine_type(url):
    if "/film" in url:
        return "Movie"
    else:
        return "Series"

merged_df["type"] = merged_df["url"].apply(determine_type)

## Cast column was split

In [94]:
data = []

for i, entry in enumerate(merged_df["cast"]):
    if not pd.isna(entry):
        for cast_dict in ast.literal_eval(entry):
            name = cast_dict['name']
            character = cast_dict['caracter']
            series_name = merged_df.loc[i, "name"]  
            data.append({"Name": name, "Character": character, "Series": series_name})

cast_df = pd.DataFrame(data)

cast_df

                 Name       Character          Series
0       Lego Lee Fang          Zi Hao  Because of You
1           Megan Lai     Yu You Tong  Because of You
2          Baron Chen         Sun Fan  Because of You
3         Jo Hyun-jae        Han Kang         49 Days
4         Bae Soo-bin     Kang Min Ho         49 Days
...               ...             ...             ...
7600     Shin Seul-ki       Seo Do-ah    Pyramid Game
7601        Ha Yul-Ri     Bang Woo-yi    Pyramid Game
7602  Hwang Hyun-jung     Kim Da-yeon    Pyramid Game
7603      Lee Ju-yeon  Shim Eun-jeong    Pyramid Game
7604        Oh Se-eun  Song Jae-hyung    Pyramid Game

[7605 rows x 3 columns]

In [96]:
cast_df["Name"].value_counts()

Name
Kim Won-hae     22
Sung Dong-il    21
Kim Sang-ho     19
Kim Hae-sook    17
Ahn Nae-sang    17
                ..
Jo Seung-Hee     1
Kim Tae-yun      1
Ji Gun Woo       1
Samuel           1
Oh Se-eun        1
Name: count, Length: 3119, dtype: int64

### Data Frame for AI

In [68]:
df_for_ai = merged_df.copy()

In [69]:
# Kategorileri içeren bir liste oluşturun
categories_list = []

# "category" sütununu işleyin
for cat_string in df_for_ai["category"]:
    # Virgülle ayrılmış kategorileri parçalayın
    categories = cat_string.split(",")
    
    # Her bir kategori için
    for category in categories:
        # Boşlukları temizleyin
        category = category.strip().lower()
        
        # Kategoriyi listeye ekleyin
        categories_list.append(category)

# Her bir kategori için yeni bir sütun oluşturun
for category in set(categories_list):
    df_for_ai[category] = df_for_ai["category"].str.contains(category, case=False).astype(int)

In [79]:
df_for_ai.drop("category",axis=1 ,inplace=True)

In [76]:
df_for_ai["type"] = df_for_ai["type"].map({"Series": 1, "Movie": 0})

In [81]:
df_for_ai.drop("url",axis=1 ,inplace=True)

In [82]:
df_for_ai

,name,total_episode,rating,like,watch,cast,year,type,polisiye,çin dizileri,...,tarih,romantik,gizem,aksiyon,dram,hukuk,korku,aile,animasyon,komedi
0,Because of You,22,7.0,11,3,"[{'name': 'Lego Lee Fang', 'caracter': 'Zi Hao...",2010,1,0,0,...,0,1,0,0,0,0,0,0,0,0
1,49 Days,20,8.4,82,64,"[{'name': 'Jo Hyun-jae', 'caracter': 'Han Kang...",2011,1,0,0,...,0,1,0,0,1,0,0,0,0,0
2,The Slave Hunters,24,7.9,46,32,"[{'name': 'Jang Hyuk', 'caracter': 'Lee Dae-gi...",2010,1,0,0,...,1,0,0,1,1,0,0,0,0,0
3,Secret Garden,20,8.9,198,150,"[{'name': 'Hyun Bin', 'caracter': 'Kim Joo-won...",2010,1,0,0,...,0,0,0,0,1,0,0,0,0,1
4,A Man Called God,24,6.7,10,9,"[{'name': 'Song Il-gook', 'caracter': 'Michael...",2010,1,0,0,...,0,1,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1003,Flex X Cop,16,9.1,77,32,"[{'name': 'Ahn Bo-hyun', 'caracter': 'Jin I-so...",2024,1,0,0,...,0,0,1,1,0,0,0,0,0,0
1004,The Midnight Studio,16,8.0,62,28,"[{'name': 'Joo Won', 'caracter': 'Seo Ki-joo'}...",2024,1,0,0,...,0,1,0,0,1,0,0,0,0,0
1005,Queen of Tears,16,8.6,58,36,"[{'name': 'Kim Soo-hyun', 'caracter': 'Baek Hy...",2024,1,0,0,...,0,1,0,0,1,0,0,0,0,0
1006,Doctor Slump,16,8.4,81,44,"[{'name': 'Park Shin-hye', 'caracter': 'Nam Ha...",2024,1,0,0,...,0,1,0,0,1,0,0,0,0,1
1007,Pyramid Game,10,8.7,46,12,"[{'name': 'Bona', 'caracter': 'Sung Su-ji'}, {...",2024,1,0,0,...,0,0,0,1,1,0,0,0,0,0